### ISSUE TITLE
Ine the command exeption

### ISSUE THREAD

**Issue by Zerbaib** [Person0z/discord.py-template#35]
the ``embed=errors.create_error_embed(f"Error sending userinfo command: {e}")`` doesn't work

**Comment by Person0z** [comment]
> the ``embed=errors.create_error_embed(f"Error sending userinfo command: {e}")`` doesn't work

What file, I need more information please.

**Comment by Person0z** [comment]
Nevermind I found the issue. I forgot the ``from helpers import errors`` on the imports

**Comment by Zerbaib** [comment]
i got to patch it thx

**Comment by Zerbaib** [comment]
done
